version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PWD}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
